# Generated by Django 4.2.5 on 2023-12-04 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPassword',
            fields=[
                ('AdminID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('AdminName', models.CharField(max_length=20)),
                ('Email_ID', models.CharField(max_length=50, unique=True)),
                ('Role', models.CharField(max_length=10)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRegister',
            fields=[
                ('F_Name', models.CharField(max_length=20)),
                ('M_Name', models.CharField(max_length=20)),
                ('L_Name', models.CharField(max_length=20)),
                ('Admission_No', models.IntegerField(primary_key=True, serialize=False)),
                ('Email_ID', models.CharField(max_length=50, unique=True)),
                ('Mobile_NO', models.IntegerField()),
                ('Course_Name', models.CharField(max_length=20)),
                ('S_Date', models.DateField()),
                ('E_Date', models.DateField()),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherRegister',
            fields=[
                ('F_Name', models.CharField(max_length=20)),
                ('M_Name', models.CharField(max_length=20)),
                ('L_Name', models.CharField(max_length=20)),
                ('Faculty_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Email_ID', models.CharField(max_length=50, unique=True)),
                ('Mobile_NO', models.IntegerField(unique=True)),
                ('Depatment_Name', models.CharField(max_length=20)),
                ('J_Date', models.DateField()),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('TimetableID', models.AutoField(primary_key=True, serialize=False)),
                ('Course_Name', models.CharField(max_length=20)),
                ('Subject', models.CharField(max_length=20)),
                ('Room_No', models.IntegerField()),
                ('Date', models.DateField()),
                ('S_Time', models.TimeField()),
                ('E_Time', models.TimeField()),
                ('Day', models.CharField(max_length=10)),
                ('Faculty_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_with_QRcode.teacherregister')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admission_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_with_QRcode.studentregister')),
                ('TimetableID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_with_QRcode.timetable')),
            ],
        ),
    ]
